import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1769000000000 implements MigrationInterface {
    name = 'Init1769000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "workspaces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" character varying, "settings" jsonb, "owner_id" uuid NOT NULL, "image_url" character varying, CONSTRAINT "UQ_b8e9fe62e93d60089dfc4f175f3" UNIQUE ("slug"), CONSTRAINT "PK_098656ae401f3e1a4586f47fd8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71bb8e4ebb814b2d8a5033aa04" ON "workspaces" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8e9fe62e93d60089dfc4f175f" ON "workspaces" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."permissions_resource_enum" AS ENUM('WORKSPACE', 'PROJECT', 'TASK', 'COMMENT', 'MEMBER', 'LABEL', 'SPRINT', 'REPORT', 'WEBHOOK', 'SETTINGS')`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum" AS ENUM('CREATE', 'READ', 'UPDATE', 'DELETE', 'MANAGE', 'ASSIGN', 'EXPORT', 'IMPORT', 'INVITE', 'REMOVE')`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "name" character varying(100) NOT NULL, "description" character varying(255), "resource" "public"."permissions_resource_enum" NOT NULL, "action" "public"."permissions_action_enum" NOT NULL, CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_337088ff813c697c964f49f58f" ON "permissions" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_48ce552495d14eae9b187bb671" ON "permissions" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_89456a09b598ce8915c702c528" ON "permissions" ("resource") `);
        await queryRunner.query(`CREATE TYPE "public"."roles_scope_enum" AS ENUM('SYSTEM', 'WORKSPACE', 'PROJECT')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "name" character varying(100) NOT NULL, "description" character varying(255), "scope" "public"."roles_scope_enum" NOT NULL DEFAULT 'WORKSPACE', "workspace_id" uuid, "is_default" boolean NOT NULL DEFAULT false, "priority" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e5a52fc6f7a8dae64f645b0914" ON "roles" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_c39d7a156a2d1e73c8be1945e9" ON "roles" ("scope") `);
        await queryRunner.query(`CREATE INDEX "IDX_5291e7ee78e540217bd44bd368" ON "roles" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."workspace_members_role_enum" AS ENUM('OWNER', 'ADMIN', 'MEMBER', 'GUEST')`);
        await queryRunner.query(`CREATE TABLE "workspace_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "message" character varying, "role" "public"."workspace_members_role_enum" NOT NULL DEFAULT 'MEMBER', "role_id" uuid, CONSTRAINT "UQ_4896b609c71ca5ad20ad662077b" UNIQUE ("user_id", "workspace_id"), CONSTRAINT "PK_22ab43ac5865cd62769121d2bc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2556b68b0a261f585bbafad129" ON "workspace_members" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e83431119fa585fc7aa8b817d" ON "workspace_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a7c584ddfe855379598b5e20f" ON "workspace_members" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd3916b233236ce65c819f8c3f" ON "workspace_members" ("role_id") `);
        await queryRunner.query(`CREATE TYPE "public"."project_members_role_enum" AS ENUM('MANAGER', 'MEMBER', 'VIEWER')`);
        await queryRunner.query(`CREATE TABLE "project_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "project_id" uuid NOT NULL, "role" "public"."project_members_role_enum" NOT NULL DEFAULT 'MEMBER', "role_id" uuid, CONSTRAINT "UQ_b3f491d3a3f986106d281d8eb4b" UNIQUE ("user_id", "project_id"), CONSTRAINT "PK_0b2f46f804be4aea9234c78bcc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc73f8b48e5a6bddc8c9c94e65" ON "project_members" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e89aae80e010c2faa72e6a49ce" ON "project_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5729113570c20c7e214cf3f58" ON "project_members" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_47b9998e6fef04f3e85e1e6094" ON "project_members" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "content" text NOT NULL, "user_id" uuid NOT NULL, "task_id" uuid NOT NULL, "parent_id" uuid, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e7c9a36c0ac867b543c6509aa" ON "comments" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c675567d2a58f0b07cef09c13" ON "comments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_18c2493067c11f44efb35ca0e0" ON "comments" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6f93329801a93536da4241e38" ON "comments" ("parent_id") `);
        await queryRunner.query(`CREATE TABLE "labels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "workspace_id" uuid NOT NULL, "name" character varying(50) NOT NULL, "color" character varying(7) NOT NULL DEFAULT '#3b82f6', "description" character varying(200), CONSTRAINT "PK_c0c4e97f76f1f3a268c7a70b925" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b77ec5d99d50bf85af486abb9c" ON "labels" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_abde089be1cb8f9ebc85211e8b" ON "labels" ("workspace_id") `);
        await queryRunner.query(`CREATE TABLE "subtasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "task_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "completed" boolean NOT NULL DEFAULT false, "position" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_035c1c153f0239ecc95be448d96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d4686a38cfe15e4ac6fbf6a9e4" ON "subtasks" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f5962cd050efba5fcc6a5d86d" ON "subtasks" ("task_id") `);
        await queryRunner.query(`CREATE TABLE "time_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "task_id" uuid NOT NULL, "user_id" uuid NOT NULL, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP, "duration" integer NOT NULL DEFAULT '0', "description" text, CONSTRAINT "PK_b8bc5f10269ba2fe88708904aa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0c787eeb1af4e5c3a4d65c2d19" ON "time_entries" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_104aa11ede7c8d5afbbe1fdbb2" ON "time_entries" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f16c3c269283ee42429d09d693" ON "time_entries" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."sprints_status_enum" AS ENUM('PLANNING', 'ACTIVE', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "sprints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "goal" character varying, "project_id" uuid NOT NULL, "status" "public"."sprints_status_enum" NOT NULL DEFAULT 'PLANNING', "start_date" TIMESTAMP, "end_date" TIMESTAMP, CONSTRAINT "PK_6800aa2e0f508561812c4b9afb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee8efbd38b74e42dc867ed25c9" ON "sprints" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_82145010051f3f2fc94671c0b3" ON "sprints" ("project_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('TODO', 'IN_PROGRESS', 'DONE', 'CLOSED', 'REOPEN')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_type_enum" AS ENUM('TASK', 'BUG', 'FEATURE', 'IMPROVEMENT', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "project_id" uuid NOT NULL, "title" character varying NOT NULL, "description" character varying, "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'TODO', "type" "public"."tasks_type_enum" NOT NULL DEFAULT 'TASK', "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'MEDIUM', "assignee_id" uuid, "due_date" TIMESTAMP, "estimated_time" integer NOT NULL DEFAULT '0', "logged_time" integer NOT NULL DEFAULT '0', "story_points" integer, "parent_task_id" character varying, "is_recurring" boolean NOT NULL DEFAULT false, "recurrence_pattern" character varying, "recurrence_end_date" TIMESTAMP, "sprint_id" uuid, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb3724030e9674f2c17b7573aa" ON "tasks" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9eecdb5b1ed8c7c2a1b392c28d" ON "tasks" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_855d484825b715c545349212c7" ON "tasks" ("assignee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_54fc42a253a8338488ec1f960a" ON "tasks" ("parent_task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b512d5a489d692f66569978b8a" ON "tasks" ("sprint_id") `);
        await queryRunner.query(`CREATE TABLE "user_refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "jti" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_7559f06f96ec3667355e233c98b" UNIQUE ("jti"), CONSTRAINT "PK_c5f5cf35bd8aabd1ebe9bb13409" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_49c4fe8fead4b8d0cdbf71dd2c" ON "user_refresh_tokens" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_15ffbf3cf712c581611caf2130" ON "user_refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7559f06f96ec3667355e233c98" ON "user_refresh_tokens" ("jti") `);
        await queryRunner.query(`CREATE TYPE "public"."users_provider_enum" AS ENUM('LOCAL', 'GOOGLE', 'GITHUB', 'GUEST')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'PENDING_DELETION', 'DELETED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "email" character varying NOT NULL, "password" character varying, "provider" "public"."users_provider_enum" NOT NULL DEFAULT 'LOCAL', "provider_id" character varying, "name" character varying, "image" character varying, "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "freeze_account_date" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c9b5b525a96ddc2c5647d7f7fa" ON "users" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."projects_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('ACTIVE', 'PLANNING', 'COMPLETED', 'ON_HOLD', 'CANCELLED', 'CLOSED', 'REOPEN')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "description" character varying, "priority" "public"."projects_priority_enum" NOT NULL DEFAULT 'MEDIUM', "status" "public"."projects_status_enum" NOT NULL DEFAULT 'PLANNING', "start_date" date, "end_date" date, "team_lead" uuid, "workspace_id" uuid NOT NULL, "progress" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_301eb04c3ee67cb2ab9cb2ab7b" ON "projects" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4926d39e950aed6e210ac1ba57" ON "projects" ("team_lead") `);
        await queryRunner.query(`CREATE INDEX "IDX_af78b8fc6857fe0a10d1bb1699" ON "projects" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."webhooks_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "webhooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "project_id" uuid NOT NULL, "name" character varying NOT NULL, "url" character varying NOT NULL, "secret" character varying, "status" "public"."webhooks_status_enum" NOT NULL DEFAULT 'ACTIVE', "events" text NOT NULL, "failure_count" integer NOT NULL DEFAULT '0', "last_triggered_at" TIMESTAMP, "last_success_at" TIMESTAMP, "last_error" text, "created_by_id" uuid NOT NULL, CONSTRAINT "PK_9e8795cfc899ab7bdaa831e8527" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de453729a7f0793dd976defc51" ON "webhooks" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b545b4c86913152b9da6e04b0" ON "webhooks" ("project_id") `);
        await queryRunner.query(`CREATE TYPE "public"."webhook_logs_event_enum" AS ENUM('task.created', 'task.updated', 'task.deleted', 'task.status_changed', 'task.assigned', 'comment.added', 'sprint.started', 'sprint.completed', 'project.member_added', 'project.member_removed')`);
        await queryRunner.query(`CREATE TYPE "public"."webhook_logs_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED', 'RETRYING')`);
        await queryRunner.query(`CREATE TABLE "webhook_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "webhook_id" uuid NOT NULL, "event" "public"."webhook_logs_event_enum" NOT NULL, "payload" jsonb NOT NULL, "status" "public"."webhook_logs_status_enum" NOT NULL DEFAULT 'PENDING', "response_status" integer, "response_body" text, "attempt_count" integer NOT NULL DEFAULT '0', "next_retry_at" TIMESTAMP, "error_message" text, "duration_ms" integer, CONSTRAINT "PK_c41f6cdf59cdfe3704807650896" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b0c7457a2a5d5b0c6b2b0b671" ON "webhook_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b8ec678bfddfab16abccafb3c" ON "webhook_logs" ("webhook_id") `);
        await queryRunner.query(`CREATE TABLE "task_watchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "user_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a9ea28114ca0842fe549b67e5d4" UNIQUE ("task_id", "user_id"), CONSTRAINT "PK_fa77927e9a914d3ed0b6726a6e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."task_templates_type_enum" AS ENUM('TASK', 'BUG', 'FEATURE', 'IMPROVEMENT', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."task_templates_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TABLE "task_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "description" character varying, "workspace_id" uuid NOT NULL, "type" "public"."task_templates_type_enum" NOT NULL DEFAULT 'TASK', "priority" "public"."task_templates_priority_enum" NOT NULL DEFAULT 'MEDIUM', "estimated_time" integer NOT NULL DEFAULT '0', "story_points" integer, "subtasks" json, "checklist" json, CONSTRAINT "PK_a1347b5446b9e3158e2b72f58b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d0ec4b674e8bbde74edbdade7" ON "task_templates" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a716007e55c1a0a9db2c56fff4" ON "task_templates" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."task_dependencies_type_enum" AS ENUM('blocks', 'blocked_by', 'relates_to', 'duplicates')`);
        await queryRunner.query(`CREATE TABLE "task_dependencies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "depends_on_task_id" uuid NOT NULL, "type" "public"."task_dependencies_type_enum" NOT NULL DEFAULT 'blocked_by', "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_34abffd156d4d10466f5f254ef2" UNIQUE ("task_id", "depends_on_task_id"), CONSTRAINT "PK_e31de0e173af595a21c4ec8e48b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "file_name" character varying NOT NULL, "original_name" character varying NOT NULL, "mime_type" character varying NOT NULL, "size" bigint NOT NULL, "url" character varying NOT NULL, "file_key" character varying, "uploaded_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_34eb9e5133310a488eaba0be28a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "saved_filters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "user_id" uuid NOT NULL, "project_id" uuid, "filters" json NOT NULL, "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d30e30ca883a3bd014c9ed983ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_74c9d1516d19acbeb98cd0d69c" ON "saved_filters" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_1072cc58f972749123491fcd77" ON "saved_filters" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0b81e0afc2a3456a8c8ff7f82" ON "saved_filters" ("project_id") `);
        await queryRunner.query(`CREATE TYPE "public"."recurring_tasks_tasktype_enum" AS ENUM('TASK', 'BUG', 'FEATURE', 'IMPROVEMENT', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."recurring_tasks_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TYPE "public"."recurring_tasks_pattern_enum" AS ENUM('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'CUSTOM')`);
        await queryRunner.query(`CREATE TYPE "public"."recurring_tasks_status_enum" AS ENUM('ACTIVE', 'PAUSED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "recurring_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "project_id" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "taskType" "public"."recurring_tasks_tasktype_enum" NOT NULL DEFAULT 'TASK', "priority" "public"."recurring_tasks_priority_enum" NOT NULL DEFAULT 'MEDIUM', "pattern" "public"."recurring_tasks_pattern_enum" NOT NULL DEFAULT 'WEEKLY', "cron_expression" character varying, "days_of_week" text, "day_of_month" integer, "status" "public"."recurring_tasks_status_enum" NOT NULL DEFAULT 'ACTIVE', "start_date" TIMESTAMP NOT NULL, "end_date" TIMESTAMP, "due_date_offset" integer NOT NULL DEFAULT '0', "estimated_time" integer, "story_points" integer, "skip_weekends" boolean NOT NULL DEFAULT false, "assignee_id" uuid, "sprint_id" character varying, "label_ids" text, "last_generated_at" TIMESTAMP, "next_generation_at" TIMESTAMP, "tasks_generated" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_9a998c7a4854b2789d988bc9750" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_effa701ccd78a01904d7749de0" ON "recurring_tasks" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_51862962b842dba8f3356391aa" ON "recurring_tasks" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "project_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "workspace_id" uuid NOT NULL, "template" json NOT NULL, "created_by" uuid NOT NULL, "is_public" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8ad4477f22e9b6e0880f1053449" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0f5bc6f6fababd5072897b92cb" ON "project_templates" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_DUE_SOON', 'TASK_OVERDUE', 'COMMENT_ADDED', 'PROJECT_CREATED', 'PROJECT_MEMBER_ADDED', 'MENTION')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "data" jsonb, "is_read" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77ee7b06d6f802000c0846f3a5" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f12148ce379462ebbb4d06cc13" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE TABLE "guest_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "ip_address" character varying NOT NULL, "device_fingerprint" character varying, "user_id" uuid NOT NULL, "expires_at" TIMESTAMP NOT NULL, "login_count" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_7c077389b040139ae9487c1b03e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3e49f109052f829e3341f2ec33" ON "guest_sessions" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c8cf61e71f31077171be9b70e" ON "guest_sessions" ("ip_address") `);
        await queryRunner.query(`CREATE INDEX "IDX_490275e79cfa6565ae4f9987ee" ON "guest_sessions" ("device_fingerprint") `);
        await queryRunner.query(`CREATE TYPE "public"."custom_fields_type_enum" AS ENUM('text', 'number', 'date', 'select', 'multi_select', 'checkbox', 'url', 'email')`);
        await queryRunner.query(`CREATE TABLE "custom_fields" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."custom_fields_type_enum" NOT NULL DEFAULT 'text', "project_id" uuid NOT NULL, "options" json, "required" boolean NOT NULL DEFAULT false, "order" integer NOT NULL DEFAULT '0', "created_by" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_35ab958a0baec2e0b2b2b875fdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eb240b445f43875d972a2cc250" ON "custom_fields" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "task_custom_field_values" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" character varying NOT NULL, "custom_field_id" uuid NOT NULL, "value" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0c9795cf23e8606f6adb2e1225d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2378b424c5ba987be308e5d7ee" ON "task_custom_field_values" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef16cb8aa650e5a0a93cb8c082" ON "task_custom_field_values" ("custom_field_id") `);
        await queryRunner.query(`CREATE TYPE "public"."file_metadata_visibility_enum" AS ENUM('public', 'private')`);
        await queryRunner.query(`CREATE TYPE "public"."file_metadata_status_enum" AS ENUM('pending', 'uploaded', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."file_metadata_file_type_enum" AS ENUM('image', 'document')`);
        await queryRunner.query(`CREATE TABLE "file_metadata" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_key" character varying NOT NULL, "original_name" character varying NOT NULL, "mime_type" character varying NOT NULL, "size" bigint NOT NULL, "visibility" "public"."file_metadata_visibility_enum" NOT NULL DEFAULT 'public', "status" "public"."file_metadata_status_enum" NOT NULL DEFAULT 'pending', "file_type" "public"."file_metadata_file_type_enum" NOT NULL DEFAULT 'image', "user_id" uuid, "url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_f6391de172dd88468183c2f3553" UNIQUE ("file_key"), CONSTRAINT "PK_b8805dd11c868561f260a0410ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."automation_rules_trigger_enum" AS ENUM('task_created', 'task_status_changed', 'task_assigned', 'task_due_date_approaching', 'task_overdue', 'subtask_completed', 'all_subtasks_completed')`);
        await queryRunner.query(`CREATE TYPE "public"."automation_rules_action_enum" AS ENUM('assign_user', 'change_status', 'change_priority', 'add_label', 'remove_label', 'send_notification', 'add_watcher', 'move_to_sprint')`);
        await queryRunner.query(`CREATE TABLE "automation_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "project_id" uuid NOT NULL, "trigger" "public"."automation_rules_trigger_enum" NOT NULL, "triggerConditions" json, "action" "public"."automation_rules_action_enum" NOT NULL, "actionParams" json NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_378bed501eacc036895837121c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfeaf4ef540ac839662335a07b" ON "automation_rules" ("project_id") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT', 'IMPORT')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_entity_type_enum" AS ENUM('USER', 'WORKSPACE', 'PROJECT', 'TASK', 'COMMENT', 'SPRINT', 'LABEL', 'ATTACHMENT', 'WEBHOOK', 'RECURRING_TASK')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "workspace_id" character varying, "project_id" character varying, "action" "public"."audit_logs_action_enum" NOT NULL, "entity_type" "public"."audit_logs_entity_type_enum" NOT NULL, "entity_id" character varying NOT NULL, "entity_name" character varying, "old_values" jsonb, "new_values" jsonb, "changed_fields" text, "metadata" jsonb, "ip_address" character varying, "user_agent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e140f8ddef870ea93925f251f2" ON "audit_logs" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e124016d61fe935a7f10ac3fa" ON "audit_logs" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_46a2bc82e4d3575f85cb44c4f3" ON "audit_logs" ("workspace_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f68e345c05e8166ff9deea1ab" ON "audit_logs" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."activities_type_enum" AS ENUM('task_created', 'task_updated', 'task_deleted', 'task_status_changed', 'task_priority_changed', 'task_assignee_changed', 'task_due_date_changed', 'comment_added', 'comment_updated', 'comment_deleted', 'subtask_added', 'subtask_completed', 'subtask_uncompleted', 'label_added', 'label_removed', 'project_created', 'project_updated', 'project_member_added', 'project_member_removed')`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying DEFAULT 'SYSTEM', "updated_by" character varying DEFAULT 'SYSTEM', "deleted_at" TIMESTAMP, "project_id" uuid NOT NULL, "task_id" uuid, "user_id" uuid NOT NULL, "type" "public"."activities_type_enum" NOT NULL, "description" text, "metadata" jsonb, CONSTRAINT "PK_7f4004429f731ffb9c88eb486a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_447bb2cdd68efb51b1ae017fa5" ON "activities" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7297db78eb572fa29db5aaf815" ON "activities" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf7d57a8dbac45bbdf52385f8b" ON "activities" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b82f1d8368dd5305ae7e7e664c" ON "activities" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "task_labels" ("task_id" uuid NOT NULL, "label_id" uuid NOT NULL, CONSTRAINT "PK_d46d4e476e3f6f8bf272b2bc1eb" PRIMARY KEY ("task_id", "label_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_844df22351eb86c33c3e8c132f" ON "task_labels" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_09dd3f6f9d04063726c498155f" ON "task_labels" ("label_id") `);
        await queryRunner.query(`ALTER TABLE "workspaces" ADD CONSTRAINT "FK_3bc45ecdd8fdc2108bb92516dde" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_5291e7ee78e540217bd44bd3688" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_4e83431119fa585fc7aa8b817db" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_4a7c584ddfe855379598b5e20fd" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ADD CONSTRAINT "FK_cd3916b233236ce65c819f8c3f0" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_47b9998e6fef04f3e85e1e60948" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_18c2493067c11f44efb35ca0e03" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_d6f93329801a93536da4241e386" FOREIGN KEY ("parent_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_abde089be1cb8f9ebc85211e8b7" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subtasks" ADD CONSTRAINT "FK_4f5962cd050efba5fcc6a5d86d6" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_104aa11ede7c8d5afbbe1fdbb24" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_f16c3c269283ee42429d09d693d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_82145010051f3f2fc94671c0b35" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_855d484825b715c545349212c7f" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_b512d5a489d692f66569978b8a7" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_refresh_tokens" ADD CONSTRAINT "FK_15ffbf3cf712c581611caf2130a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_4926d39e950aed6e210ac1ba576" FOREIGN KEY ("team_lead") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD CONSTRAINT "FK_8b545b4c86913152b9da6e04b08" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD CONSTRAINT "FK_04060f01849c1c9ca048094a7b4" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_logs" ADD CONSTRAINT "FK_0b8ec678bfddfab16abccafb3c7" FOREIGN KEY ("webhook_id") REFERENCES "webhooks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_watchers" ADD CONSTRAINT "FK_6ec69c77281f4bc0a18fdbc722a" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_watchers" ADD CONSTRAINT "FK_ff976f3fc177614cc4a60291de1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_templates" ADD CONSTRAINT "FK_a716007e55c1a0a9db2c56fff42" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_26dedda08faccdb95aff99e112e" FOREIGN KEY ("depends_on_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_4a251b37965df3adc13d3f37ddb" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_attachments" ADD CONSTRAINT "FK_8c07320adec50a39744a4a301d3" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_attachments" ADD CONSTRAINT "FK_0bde6a97fd0578e6ae7fb637495" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_filters" ADD CONSTRAINT "FK_1072cc58f972749123491fcd776" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_filters" ADD CONSTRAINT "FK_a0b81e0afc2a3456a8c8ff7f82b" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_tasks" ADD CONSTRAINT "FK_51862962b842dba8f3356391aa7" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_tasks" ADD CONSTRAINT "FK_118962e1f008639c514e1122a4e" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_templates" ADD CONSTRAINT "FK_0f5bc6f6fababd5072897b92cba" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_templates" ADD CONSTRAINT "FK_d6dbb45e902721a3a0a81a6e95b" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guest_sessions" ADD CONSTRAINT "FK_ac427886a0f8018bba5da1815c3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_fields" ADD CONSTRAINT "FK_eb240b445f43875d972a2cc250e" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_custom_field_values" ADD CONSTRAINT "FK_ef16cb8aa650e5a0a93cb8c0825" FOREIGN KEY ("custom_field_id") REFERENCES "custom_fields"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_metadata" ADD CONSTRAINT "FK_d05f79b7826b451ea35f11fe499" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "automation_rules" ADD CONSTRAINT "FK_cfeaf4ef540ac839662335a07b7" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "automation_rules" ADD CONSTRAINT "FK_ce42f8b01e27f214e31311e6c8b" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_7297db78eb572fa29db5aaf8158" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_bf7d57a8dbac45bbdf52385f8b8" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_b82f1d8368dd5305ae7e7e664c2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_labels" ADD CONSTRAINT "FK_844df22351eb86c33c3e8c132f4" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_labels" ADD CONSTRAINT "FK_09dd3f6f9d04063726c498155f2" FOREIGN KEY ("label_id") REFERENCES "labels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_labels" DROP CONSTRAINT "FK_09dd3f6f9d04063726c498155f2"`);
        await queryRunner.query(`ALTER TABLE "task_labels" DROP CONSTRAINT "FK_844df22351eb86c33c3e8c132f4"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_b82f1d8368dd5305ae7e7e664c2"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_bf7d57a8dbac45bbdf52385f8b8"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_7297db78eb572fa29db5aaf8158"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "automation_rules" DROP CONSTRAINT "FK_ce42f8b01e27f214e31311e6c8b"`);
        await queryRunner.query(`ALTER TABLE "automation_rules" DROP CONSTRAINT "FK_cfeaf4ef540ac839662335a07b7"`);
        await queryRunner.query(`ALTER TABLE "file_metadata" DROP CONSTRAINT "FK_d05f79b7826b451ea35f11fe499"`);
        await queryRunner.query(`ALTER TABLE "task_custom_field_values" DROP CONSTRAINT "FK_ef16cb8aa650e5a0a93cb8c0825"`);
        await queryRunner.query(`ALTER TABLE "custom_fields" DROP CONSTRAINT "FK_eb240b445f43875d972a2cc250e"`);
        await queryRunner.query(`ALTER TABLE "guest_sessions" DROP CONSTRAINT "FK_ac427886a0f8018bba5da1815c3"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "project_templates" DROP CONSTRAINT "FK_d6dbb45e902721a3a0a81a6e95b"`);
        await queryRunner.query(`ALTER TABLE "project_templates" DROP CONSTRAINT "FK_0f5bc6f6fababd5072897b92cba"`);
        await queryRunner.query(`ALTER TABLE "recurring_tasks" DROP CONSTRAINT "FK_118962e1f008639c514e1122a4e"`);
        await queryRunner.query(`ALTER TABLE "recurring_tasks" DROP CONSTRAINT "FK_51862962b842dba8f3356391aa7"`);
        await queryRunner.query(`ALTER TABLE "saved_filters" DROP CONSTRAINT "FK_a0b81e0afc2a3456a8c8ff7f82b"`);
        await queryRunner.query(`ALTER TABLE "saved_filters" DROP CONSTRAINT "FK_1072cc58f972749123491fcd776"`);
        await queryRunner.query(`ALTER TABLE "task_attachments" DROP CONSTRAINT "FK_0bde6a97fd0578e6ae7fb637495"`);
        await queryRunner.query(`ALTER TABLE "task_attachments" DROP CONSTRAINT "FK_8c07320adec50a39744a4a301d3"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_4a251b37965df3adc13d3f37ddb"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_26dedda08faccdb95aff99e112e"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707"`);
        await queryRunner.query(`ALTER TABLE "task_templates" DROP CONSTRAINT "FK_a716007e55c1a0a9db2c56fff42"`);
        await queryRunner.query(`ALTER TABLE "task_watchers" DROP CONSTRAINT "FK_ff976f3fc177614cc4a60291de1"`);
        await queryRunner.query(`ALTER TABLE "task_watchers" DROP CONSTRAINT "FK_6ec69c77281f4bc0a18fdbc722a"`);
        await queryRunner.query(`ALTER TABLE "webhook_logs" DROP CONSTRAINT "FK_0b8ec678bfddfab16abccafb3c7"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP CONSTRAINT "FK_04060f01849c1c9ca048094a7b4"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP CONSTRAINT "FK_8b545b4c86913152b9da6e04b08"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_4926d39e950aed6e210ac1ba576"`);
        await queryRunner.query(`ALTER TABLE "user_refresh_tokens" DROP CONSTRAINT "FK_15ffbf3cf712c581611caf2130a"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_b512d5a489d692f66569978b8a7"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_855d484825b715c545349212c7f"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_82145010051f3f2fc94671c0b35"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_f16c3c269283ee42429d09d693d"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_104aa11ede7c8d5afbbe1fdbb24"`);
        await queryRunner.query(`ALTER TABLE "subtasks" DROP CONSTRAINT "FK_4f5962cd050efba5fcc6a5d86d6"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_abde089be1cb8f9ebc85211e8b7"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_d6f93329801a93536da4241e386"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_18c2493067c11f44efb35ca0e03"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_47b9998e6fef04f3e85e1e60948"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_cd3916b233236ce65c819f8c3f0"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_4a7c584ddfe855379598b5e20fd"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" DROP CONSTRAINT "FK_4e83431119fa585fc7aa8b817db"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_5291e7ee78e540217bd44bd3688"`);
        await queryRunner.query(`ALTER TABLE "workspaces" DROP CONSTRAINT "FK_3bc45ecdd8fdc2108bb92516dde"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09dd3f6f9d04063726c498155f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_844df22351eb86c33c3e8c132f"`);
        await queryRunner.query(`DROP TABLE "task_labels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b82f1d8368dd5305ae7e7e664c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf7d57a8dbac45bbdf52385f8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7297db78eb572fa29db5aaf815"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_447bb2cdd68efb51b1ae017fa5"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP TYPE "public"."activities_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f68e345c05e8166ff9deea1ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46a2bc82e4d3575f85cb44c4f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e124016d61fe935a7f10ac3fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e140f8ddef870ea93925f251f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfeaf4ef540ac839662335a07b"`);
        await queryRunner.query(`DROP TABLE "automation_rules"`);
        await queryRunner.query(`DROP TYPE "public"."automation_rules_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."automation_rules_trigger_enum"`);
        await queryRunner.query(`DROP TABLE "file_metadata"`);
        await queryRunner.query(`DROP TYPE "public"."file_metadata_file_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."file_metadata_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."file_metadata_visibility_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef16cb8aa650e5a0a93cb8c082"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2378b424c5ba987be308e5d7ee"`);
        await queryRunner.query(`DROP TABLE "task_custom_field_values"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb240b445f43875d972a2cc250"`);
        await queryRunner.query(`DROP TABLE "custom_fields"`);
        await queryRunner.query(`DROP TYPE "public"."custom_fields_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_490275e79cfa6565ae4f9987ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c8cf61e71f31077171be9b70e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e49f109052f829e3341f2ec33"`);
        await queryRunner.query(`DROP TABLE "guest_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f12148ce379462ebbb4d06cc13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77ee7b06d6f802000c0846f3a5"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f5bc6f6fababd5072897b92cb"`);
        await queryRunner.query(`DROP TABLE "project_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51862962b842dba8f3356391aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_effa701ccd78a01904d7749de0"`);
        await queryRunner.query(`DROP TABLE "recurring_tasks"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_tasks_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_tasks_pattern_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_tasks_tasktype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0b81e0afc2a3456a8c8ff7f82"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1072cc58f972749123491fcd77"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74c9d1516d19acbeb98cd0d69c"`);
        await queryRunner.query(`DROP TABLE "saved_filters"`);
        await queryRunner.query(`DROP TABLE "task_attachments"`);
        await queryRunner.query(`DROP TABLE "task_dependencies"`);
        await queryRunner.query(`DROP TYPE "public"."task_dependencies_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a716007e55c1a0a9db2c56fff4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d0ec4b674e8bbde74edbdade7"`);
        await queryRunner.query(`DROP TABLE "task_templates"`);
        await queryRunner.query(`DROP TYPE "public"."task_templates_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."task_templates_type_enum"`);
        await queryRunner.query(`DROP TABLE "task_watchers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b8ec678bfddfab16abccafb3c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b0c7457a2a5d5b0c6b2b0b671"`);
        await queryRunner.query(`DROP TABLE "webhook_logs"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_logs_event_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b545b4c86913152b9da6e04b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de453729a7f0793dd976defc51"`);
        await queryRunner.query(`DROP TABLE "webhooks"`);
        await queryRunner.query(`DROP TYPE "public"."webhooks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af78b8fc6857fe0a10d1bb1699"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4926d39e950aed6e210ac1ba57"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_301eb04c3ee67cb2ab9cb2ab7b"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."projects_priority_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9b5b525a96ddc2c5647d7f7fa"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7559f06f96ec3667355e233c98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15ffbf3cf712c581611caf2130"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49c4fe8fead4b8d0cdbf71dd2c"`);
        await queryRunner.query(`DROP TABLE "user_refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b512d5a489d692f66569978b8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54fc42a253a8338488ec1f960a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_855d484825b715c545349212c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9eecdb5b1ed8c7c2a1b392c28d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb3724030e9674f2c17b7573aa"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82145010051f3f2fc94671c0b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee8efbd38b74e42dc867ed25c9"`);
        await queryRunner.query(`DROP TABLE "sprints"`);
        await queryRunner.query(`DROP TYPE "public"."sprints_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f16c3c269283ee42429d09d693"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_104aa11ede7c8d5afbbe1fdbb2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c787eeb1af4e5c3a4d65c2d19"`);
        await queryRunner.query(`DROP TABLE "time_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f5962cd050efba5fcc6a5d86d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4686a38cfe15e4ac6fbf6a9e4"`);
        await queryRunner.query(`DROP TABLE "subtasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abde089be1cb8f9ebc85211e8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b77ec5d99d50bf85af486abb9c"`);
        await queryRunner.query(`DROP TABLE "labels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6f93329801a93536da4241e38"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18c2493067c11f44efb35ca0e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c675567d2a58f0b07cef09c13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e7c9a36c0ac867b543c6509aa"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47b9998e6fef04f3e85e1e6094"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5729113570c20c7e214cf3f58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e89aae80e010c2faa72e6a49ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc73f8b48e5a6bddc8c9c94e65"`);
        await queryRunner.query(`DROP TABLE "project_members"`);
        await queryRunner.query(`DROP TYPE "public"."project_members_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd3916b233236ce65c819f8c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a7c584ddfe855379598b5e20f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e83431119fa585fc7aa8b817d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2556b68b0a261f585bbafad129"`);
        await queryRunner.query(`DROP TABLE "workspace_members"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_members_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5291e7ee78e540217bd44bd368"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c39d7a156a2d1e73c8be1945e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5a52fc6f7a8dae64f645b0914"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_scope_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89456a09b598ce8915c702c528"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48ce552495d14eae9b187bb671"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_337088ff813c697c964f49f58f"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_resource_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8e9fe62e93d60089dfc4f175f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71bb8e4ebb814b2d8a5033aa04"`);
        await queryRunner.query(`DROP TABLE "workspaces"`);
    }

}
